language: java
jdk:
  - oraclejdk8
  
addons:
  sonarcloud:
    organization: joseluisluri-github
    token:
      secure: $SONARCLOUD_TOKEN
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
